### ISSUE TITLE
GIF for README

### ISSUE THREAD

**Issue by birdie-github** [nanochess/RayTracer#4]
Obviously just 256 colors but enough to get the idea.

![res](https://github.com/nanochess/RayTracer/assets/4958603/866f298b-b3d5-49cc-b508-9817493d14e3)

And MP4 for good measure:

https://github.com/nanochess/RayTracer/assets/4958603/d44dec2e-d0b6-4efe-9596-2ac6c4e4dc73

**Comment by nanochess** [comment]
Cool! I like your GIF file, it is a ton of effort converting these. Thanks! I've put it in the README.md
